version: '2'

services:

  worker:
    build:
      context: .
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - back-tier

  redis:
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    networks:
      - back-tier

  db:
      image: postgres:9.4
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
      volumes:
        - "./:/app"
        - "./healthchecks:/healthchecks"
      networks:
        - back-tier
      healthcheck:
        test: /healthchecks/postgres.sh
        interval: "5s"


volumes:
  db-data:

networks:
  front-tier:
  back-tier: